[package]
name = "teff"
version = "0.1.0"
authors = ["Yasuhiro Fujii <y-fujii@mimosa-pudica.net>"]
edition = "2018"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false

[dependencies]
arr_macro = "*"
rand = "*"
rayon = "*"
